<?php
$z[0]=Array("flink","  [field:link /]  ",58,136);
$z[0][4]=array();
$z[0][4]['titlelen']="20";
$z[0][4]['row']="20";
$z[0][4]['type']="text";
$z[1]=Array("global","",182,204);
$z[1][4]=array();
$z[1][4]['name']="cfg_add";
$z[2]=Array("global","",227,249);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",272,294);
$z[3][4]=array();
$z[3][4]['name']="cfg_fax";
$z[4]=Array("global","",336,362);
$z[4][4]=array();
$z[4][4]['name']="cfg_powerby";
$z[5]=Array("global","",567,591);
$z[5][4]=array();
$z[5][4]['name']="cfg_beian";
$z[6]=Array("global","",611,635);
$z[6][4]=array();
$z[6][4]['name']="cfg_beian";

?>