<?php
$z[0]=Array("global","",60,86);
$z[0][4]=array();
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",126,152);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",253,275);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("channel","\r\n    <li><a href=\"[field:typeurl/]\" title=\"[field:typename/]\">[field:typename/]</a></li>\r\n    ",408,633);
$z[3][4]=array();
$z[3][4]['type']="top";
$z[3][4]['currentstyle']="<li><a href='~typelink~' class='thisclass'>~typename~</a></li>";
$z[4]=Array("global","",851,872);
$z[4][4]=array();
$z[4][4]['name']="cfg_gg";
$z[5]=Array("global","",949,974);
$z[5][4]=array();
$z[5][4]['name']="cfg_cmsurl";

?>