<?php
$z[0]=Array("type","\r\n  <div class=\"lefttitle\">[field:typename/]</div>\r\n  ",19,108);
$z[0][4]=array();
$z[0][4]['typeid']="13";
$z[1]=Array("arclist","\r\n    <li><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></li>\r\n    ",139,308);
$z[1][4]=array();
$z[1][4]['typeid']="13";
$z[1][4]['row']="5";
$z[1][4]['titlelen']="32";
$z[1][4]['orderby']="pubdate";
$z[2]=Array("type","\r\n  <div class=\"lefttitle\">[field:typename/]</div>\r\n  ",321,410);
$z[2][4]=array();
$z[2][4]['typeid']="12";
$z[3]=Array("global","",457,479);
$z[3][4]=array();
$z[3][4]['name']="cfg_add";
$z[4]=Array("global","",501,523);
$z[4][4]=array();
$z[4][4]['name']="cfg_tel";
$z[5]=Array("global","",545,567);
$z[5][4]=array();
$z[5][4]['name']="cfg_fax";
$z[6]=Array("global","",589,613);
$z[6][4]=array();
$z[6][4]['name']="cfg_phone";
$z[7]=Array("global","",635,659);
$z[7][4]=array();
$z[7][4]['name']="cfg_email";

?>